Ruby Practice Codes week one
shaistaabidd/ror-training pull request #1
Opened 2021-08-30 12:07 UTC by shaistaabidd

Essential Ruby Training Course Part#1 Practice Problems

2021-09-07 07:48 UTC, thejunaidiqbal1 commented
Feedback:
- Don't use name of variables like ruby keywords
- Change Q12 (Japanese word game Shiritori) to basic ruby concept
- Follow the identation. Check Q24 in iterator part and replace it with correct format
- Explore the Join method with pasing parameters and without passing
- Problem 9 on week2.rb file: your output didn't match with sample outputs, and your complexity of this problem is "n^3 + n^4" so try to reduce the complexity and I think this will work with the complexity of "n"
- Next time, make separate file of every challenge/question

2021-09-13 06:20 UTC, thejunaidiqbal1 commented
Feedback:
- Refactor code of calendar (make separate methods of months, year and days)

2021-09-21 09:09 UTC, Moiz1524 requested changes
@shaistaabidd I've reviewed 18 of your problems and added inline reviews. Please implement this feedback, learn from it and revert back. Also make sure to review the remaining problems here. If they have some issues as I pointed; Go ahead and resolve them for sure. Thanks!

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/alphabets_to_num.rb
> +def alph_num(str)
@shaistaabidd Would love to see a looping structure here just to populate our `alpha` hash

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/current_date.rb
> +cdt = current_time.strftime "%d/%m/%Y %H:%M"
That should be more verbose

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/filter_array.rb
> +    arr.select{|i| i.class==Integer}
Try to use `Object.is_a?(class_name)` method!

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/first_tuesday_of_the_month.rb
> +    hash_date={
There should be some automated structure to produce the hash!

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/friday_thirteen.rb
> +def how_unlucky(year)
requiring a library inside a method is not a good approach. Imagine about multiple calls to this method. Every time you'll end up requiring, eventually wasting your resources (unused)!

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/hash_to_sym.rb
> +print hash.map { |k,v| [k, v.to_sym]}.to_h
Should we use `transform_values!` on hash here? For now we are doing these things which are kinda excessive:
1. Convert hash to array via `map`
2. Inside `map` converting each value to symbol via `to_sym`
3. And then finally converting the array into hash via `to_h`

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/inclusive_range.rb
> +    return ((a >= 420 && a <= 630) || (b >= 420 && b <= 630));
Make use of `include?` here

2021-09-21 09:09 UTC, Moiz1524 commented on Challenges_week3/is_palindrome.rb
> +    if str == str.reverse
It can be refactored with just single liner condition here. No need to explicitly return `true` and `false` inside `if - else` block

2021-09-22 08:36 UTC, merged